# fly.toml app configuration file generated for full-stack-open-pokedex3 on 2024-03-18T11:11:14+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'full-stack-open-pokedex3'
primary_region = 'ams'

[env]
PORT = "3000"

[processes]
  app = "node app.js" # add this

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']


[[http_service.checks]]
  grace_period = "120s"
  interval = "240s"
  method = "GET"
  timeout = "10s"
  path = "/health"

[deploy]
  strategy = "bluegreen"
 

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
